// Utility functions for handling image carousels

export interface ImageCarouselConfig {
  directory: string;
  supportedFormats: string[];
  excludePatterns?: string[];
}

export const getImageList = (config: ImageCarouselConfig): string[] => {
  // In a real implementation, this would scan the filesystem
  // For now, we'll return a predefined list that can be easily updated
  const { directory } = config;

  // This would typically be generated by a build script or API
  // Updated to match actual files in the directory
  const knownImages = [
    "IMG_4407.jpeg",
    "IMG_4412.jpeg",
    "1011384882698293975.jpeg",
  ];

  return knownImages.map((img) => `${directory}/${img}`);
};

export const createImageCarouselConfig = (
  directory: string = "/about-us",
  supportedFormats: string[] = [".jpeg", ".jpg", ".png", ".webp"],
): ImageCarouselConfig => ({
  directory,
  supportedFormats,
  excludePatterns: ["thumbnail", "preview", "icon"],
});

// Helper to validate image paths
export const isValidImagePath = (
  path: string,
  config: ImageCarouselConfig,
): boolean => {
  const { supportedFormats, excludePatterns = [] } = config;

  const hasValidExtension = supportedFormats.some((format) =>
    path.toLowerCase().endsWith(format.toLowerCase()),
  );

  const isExcluded = excludePatterns.some((pattern) =>
    path.toLowerCase().includes(pattern.toLowerCase()),
  );

  return hasValidExtension && !isExcluded;
};
